### ISSUE TITLE
evertime i try to do pip install -r requirements.txt it says

### ISSUE THREAD

**Issue by fghfyhfgdhjhnjg** [0xRose/Rose-RAT#10]
error: externally-managed-environment

× This environment is externally managed
╰─> This command has been disabled as it tries to modify the immutable
    `/nix/store` filesystem.
    
    To use Python with Nix and nixpkgs, have a look at the online documentation:
    <https://nixos.org/manual/nixpkgs/stable/#python>.

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.

**Comment by Erder00** [comment]
nixos moment, you're supposed to use it with replit
